name: Action1

on: [push, workflow_dispatch]

jobs:
    firstJob:
        runs-on: ubuntu-latest
        
        steps:

        - uses: actions/checkout@v4

        - name: Welcome message And show files
          run: |
            echo "Running the action file"
            ls
            tree
        
              
    