name: Action1

on: [push, workflow_dispatch]

jobs:
    firstJob:
        runs-on: ubuntu-latest
        
        steps:
        
        - name: Welcome message
          run: echo "Hi this is a message from the first step of first job"

        - uses: actions/checkout@v4
        
        - name: List Files
          run: ls
        
        - name: Tree structure of project
          run: tree    
              
    